version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#  webserver:
#    build: .
#    ports:
#      - "9000:9000"